var factionLookupNumber=new Map([
	[`Bunrodea`,11],
	[`Coalition`,12],
	[`Drak`,13],
	[`Gegno`,14],
	[`Hai`,15],
	[`Human`,16],
	[`Ka'het`,17],
	[`Korath`,18],
	[`Pug`,19],
	[`Quarg`,20],
	[`Remnant`,21],
	[`Rulei`,22],
	[`Sheragi`,23],
	[`Vyrmeid`,24],
	[`Wanderer`,25],
	[`Whispering Void`,26],
	[`???`,27]
])
var factionLookupString=new Map([
	[`"Shield Relay Booster"`,`Bunrodea`],
	[`"Shield Relay Limiter"`,`Bunrodea`],
	[`"Small Shield Relay"`,`Bunrodea`],
	[`"Large Shield Relay"`,`Bunrodea`],
	[`"Nanite Enhancer"`,`Bunrodea`],
	[`"Nanite Limiter"`,`Bunrodea`],
	[`"Small Nanite Fabricator"`,`Bunrodea`],
	[`"Large Nanite Fabricator"`,`Bunrodea`],
	[`"Solar Battery"`,`Bunrodea`],
	[`"Solar Cell"`,`Bunrodea`],
	[`"Reactor Overclocker"`,`Bunrodea`],
	[`"Reactor Limiter"`,`Bunrodea`],
	[`"Quark Reactor"`,`Bunrodea`],
	[`"Electroweak Reactor"`,`Bunrodea`],
	[`"Dark Reactor"`,`Bunrodea`],
	[`"Lasher Pistol"`,`Bunrodea`],
	[`"Chiisana Rift Thruster"`,`Bunrodea`],
	[`"Nami Rift Thruster"`,`Bunrodea`],
	[`"Ookii Rift Thruster"`,`Bunrodea`],
	[`"Subarashii Rift Thruster"`,`Bunrodea`],
	[`"Chiisana Rift Steering"`,`Bunrodea`],
	[`"Nami Rift Steering"`,`Bunrodea`],
	[`"Ookii Rift Steering"`,`Bunrodea`],
	[`"Subarashii Rift Steering"`,`Bunrodea`],
	[`"Locust Blaster"`,`Bunrodea`],
	[`"Locust Turret"`,`Bunrodea`],
	[`"Mandible Cannon"`,`Bunrodea`],
	[`"Thorax Cannon"`,`Bunrodea`],
	[`"Swarm Clip"`,`Bunrodea`],
	[`"Swarm Missile"`,`Bunrodea`],
	[`"Swarm Pod"`,`Bunrodea`],
	[`"Buzzer Anti-Missile"`,`Bunrodea`],
	[`"Small Collector Module"`,`Coalition`],
	[`"Large Collector Module"`,`Coalition`],
	[`"Small Reactor Module"`,`Coalition`],
	[`"Large Reactor Module"`,`Coalition`],
	[`"Small Cogeneration Module"`,`Coalition`],
	[`"Large Cogeneration Module"`,`Coalition`],
	[`"Small Battery Module"`,`Coalition`],
	[`"Large Battery Module"`,`Coalition`],
	[`"Small Shield Module"`,`Coalition`],
	[`"Large Shield Module"`,`Coalition`],
	[`"Overcharged Shield Module"`,`Coalition`],
	[`"Small Repair Module"`,`Coalition`],
	[`"Large Repair Module"`,`Coalition`],
	[`"Overclocked Repair Module"`,`Coalition`],
	[`"Cooling Module"`,`Coalition`],
	[`"Fuel Module"`,`Coalition`],
	[`"Scanning Module"`,`Coalition`],
	[`"Outskirts Gauger"`,`Coalition`],
	[`"Small Thrust Module"`,`Coalition`],
	[`"Large Thrust Module"`,`Coalition`],
	[`"Small Reverse Module"`,`Coalition`],
	[`"Large Reverse Module"`,`Coalition`],
	[`"Small Steering Module"`,`Coalition`],
	[`"Large Steering Module"`,`Coalition`],
	[`"Enforcer Confrontation Gear"`,`Coalition`],
	[`"Enforcer Riot Staff"`,`Coalition`],
	[`"Coalition License"`,`Coalition`],
	[`"Bombardment Cannon"`,`Coalition`],
	[`"Bombardment Turret"`,`Coalition`],
	[`"Finisher Pod"`,`Coalition`],
	[`"Finisher Maegrolain"`,`Coalition`],
	[`"Active Finisher"`,`Coalition`],
	[`"Finisher Storage Tube"`,`Coalition`],
	[`"Finisher Torpedo"`,`Coalition`],
	[`"Heliarch Attractor"`,`Coalition`],
	[`"Heliarch Repulsor"`,`Coalition`],
	[`"Ion Hail Turret"`,`Coalition`],
	[`"ion hail"`,`Coalition`],
	[`"Ion Rain Gun"`,`Coalition`],
	[`"MCS Extractor"`,`Coalition`],
	[`"Drak Distancer"`,`Drak`],
	[`"Drak Draining Field"`,`Drak`],
	[`"Drak Draining Field (Augmented)"`,`Drak`],
	[`"Drak Anti-Missile Field"`,`Drak`],
	[`"Drak Anti-Missile Field (Augmented)"`,`Drak`],
	[`"Drak Turret"`,`Drak`],
	[`"Drak Turret (Augmented)"`,`Drak`],
	[`"Drak Antimatter Cannon"`,`Drak`],
	[`"Drak Antimatter Cannon (Augmented)"`,`Drak`],
	[`"Drak Antimatter Fragment"`,`Drak`],
	[`"Drak Antimatter Fragment (Augmented)"`,`Drak`],
	[`"R01 Skirmish Battery"`,`Gegno`],
	[`"R02 Battlezone Battery"`,`Gegno`],
	[`"R03 Warforge Battery"`,`Gegno`],
	[`"R04 Crusade Battery"`,`Gegno`],
	[`"C3 Scrap Cell"`,`Gegno`],
	[`"C7 Brawl Cell"`,`Gegno`],
	[`"C17 Warzone Core"`,`Gegno`],
	[`"C27 Campaign Core"`,`Gegno`],
	[`"I70 Ameliorate Cell"`,`Gegno`],
	[`"RG15 Torch Thruster"`,`Gegno`],
	[`"RG15 Torch Steering"`,`Gegno`],
	[`"RG18 Torch Thruster"`,`Gegno`],
	[`"RG18 Torch Steering"`,`Gegno`],
	[`"RG3 Torch Thruster"`,`Gegno`],
	[`"RG3 Torch Steering"`,`Gegno`],
	[`"SC-1 Plasma Engines"`,`Gegno`],
	[`"SC-12 Plasma Thruster"`,`Gegno`],
	[`"SC-12 Plasma Steering"`,`Gegno`],
	[`"SC-14 Plasma Thruster"`,`Gegno`],
	[`"SC-14 Plasma Steering"`,`Gegno`],
	[`"SC-15 Plasma Thrusters"`,`Gegno`],
	[`"Irate Cannon"`,`Gegno`],
	[`"Irate Cannon Turret"`,`Gegno`],
	[`"Choleric Cannon"`,`Gegno`],
	[`"Choleric Cannon Turret"`,`Gegno`],
	[`"Ballistic Cannon"`,`Gegno`],
	[`"Ballistic Cannon Turret"`,`Gegno`],
	[`"Astuit Battery"`,`Gegno`],
	[`"Acuit Artillery"`,`Gegno`],
	[`"Acumen Bolt Cannon"`,`Gegno`],
	[`"Guile Pulse Laser"`,`Gegno`],
	[`"Excavator"`,`Gegno`],
	[`"Burrower"`,`Gegno`],
	[`"Ion Torch"`,`Gegno`],
	[`"Savagery Bludgeon"`,`Gegno`],
	[`"Savagery Pike"`,`Gegno`],
	[`"Irate Carronade"`,`Gegno`],
	[`"Plasmasickle"`,`Gegno`],
	[`"Plasma Grenades"`,`Gegno`],
	[`"Gegno Civilian License"`,`Gegno`],
	[`"Gegno Driller License"`,`Gegno`],
	[`"Vi Lord License"`,`Gegno`],
	[`"Vi Centurion License"`,`Gegno`],
	[`"Vi Evocati License"`,`Gegno`],
	[`"Scin Hoplologist License"`,`Gegno`],
	[`"Scin Architect License"`,`Gegno`],
	[`"Scin Adjutant License"`,`Gegno`],
	[`"Pulse Cannon"`,`Hai`],
	[`"Pulse Turret"`,`Hai`],
	[`"Tripulse Shredder"`,`Hai`],
	[`"Ion Cannon"`,`Hai`],
	[`"Ionic Blaster Prototype"`,`Hai`],
	[`"Ionic Turret Prototype"`,`Hai`],
	[`"Railgun Slug"`,`Hai`],
	[`"Railgun Slug Rack"`,`Hai`],
	[`"Railgun"`,`Hai`],
	[`"rslug"`,`Hai`],
	[`"Hai Tracker"`,`Hai`],
	[`"Tracker Storage Pod"`,`Hai`],
	[`"Hai Tracker Pod"`,`Hai`],
	[`"Bullfrog Anti-Missile"`,`Hai`],
	[`"Chameleon Anti-Missile"`,`Hai`],
	[`"Hai Cuttlefish Jammer"`,`Hai`],
	[`"Hai Octopus Jammer"`,`Hai`],
	[`"Hai Corundum Regenerator"`,`Hai`],
	[`"Hai Diamond Regenerator"`,`Hai`],
	[`"Hai Williwaw Cooling"`,`Hai`],
	[`"Quantum Keystone"`,`Hai`],
	[`"Value Detector"`,`Hai`],
	[`"Hai Chasm Batteries"`,`Hai`],
	[`"Hai Fissure Batteries"`,`Hai`],
	[`"Hai Gorge Batteries"`,`Hai`],
	[`"Hai Ravine Batteries"`,`Hai`],
	[`"Hai Valley Batteries"`,`Hai`],
	[`"Boulder Reactor"`,`Hai`],
	[`"Geode Reactor"`,`Hai`],
	[`"Pebble Core"`,`Hai`],
	[`"Sand Cell"`,`Hai`],
	[`"Pulse Rifle"`,`Hai`],
	[`"Shield Beetle Pendant"`,`Hai`],
	[`"Failed Control System"`,`Hai`],
	[`"Volcano Afterburner"`,`Human`],
	[`"Caldera Afterburner"`,`Human`],
	[`"Ionic Afterburner"`,`Human`],
	[`"X1050 Ion Engines"`,`Human`],
	[`"X1700 Ion Thruster"`,`Human`],
	[`"X2700 Ion Thruster"`,`Human`],
	[`"X3700 Ion Thruster"`,`Human`],
	[`"X4700 Ion Thruster"`,`Human`],
	[`"X5700 Ion Thruster"`,`Human`],
	[`"X1200 Ion Steering"`,`Human`],
	[`"X2200 Ion Steering"`,`Human`],
	[`"X3200 Ion Steering"`,`Human`],
	[`"X4200 Ion Steering"`,`Human`],
	[`"X5200 Ion Steering"`,`Human`],
	[`"X1100 Ion Reverse Thruster"`,`Human`],
	[`"Chipmunk Plasma Thruster"`,`Human`],
	[`"Greyhound Plasma Thruster"`,`Human`],
	[`"Impala Plasma Thruster"`,`Human`],
	[`"Orca Plasma Thruster"`,`Human`],
	[`"Tyrant Plasma Thruster"`,`Human`],
	[`"Chipmunk Plasma Steering"`,`Human`],
	[`"Greyhound Plasma Steering"`,`Human`],
	[`"Impala Plasma Steering"`,`Human`],
	[`"Orca Plasma Steering"`,`Human`],
	[`"Tyrant Plasma Steering"`,`Human`],
	[`"Capybara Reverse Thruster"`,`Human`],
	[`"A120 Atomic Thruster"`,`Human`],
	[`"A250 Atomic Thruster"`,`Human`],
	[`"A370 Atomic Thruster"`,`Human`],
	[`"A520 Atomic Thruster"`,`Human`],
	[`"A860 Atomic Thruster"`,`Human`],
	[`"A125 Atomic Steering"`,`Human`],
	[`"A255 Atomic Steering"`,`Human`],
	[`"A375 Atomic Steering"`,`Human`],
	[`"A525 Atomic Steering"`,`Human`],
	[`"A865 Atomic Steering"`,`Human`],
	[`"AR120 Reverse Thruster"`,`Human`],
	[`"Cooling Ducts"`,`Human`],
	[`"Water Coolant System"`,`Human`],
	[`"Liquid Nitrogen Cooler"`,`Human`],
	[`"Liquid Helium Cooler"`,`Human`],
	[`"D14-RN Shield Generator"`,`Human`],
	[`"D23-QP Shield Generator"`,`Human`],
	[`"D41-HY Shield Generator"`,`Human`],
	[`"D67-TM Shield Generator"`,`Human`],
	[`"D94-YV Shield Generator"`,`Human`],
	[`"S-270 Regenerator"`,`Human`],
	[`"S-970 Regenerator"`,`Human`],
	[`"Small Radar Jammer"`,`Human`],
	[`"Large Radar Jammer"`,`Human`],
	[`"Ramscoop"`,`Human`],
	[`"Catalytic Ramscoop"`,`Human`],
	[`"Hyperdrive"`,`Human`],
	[`"Scram Drive"`,`Human`],
	[`"Jump Drive"`,`Human`],
	[`"Jump Drive (Broken)"`,`Human`],
	[`"Cargo Scanner"`,`Human`],
	[`"Outfit Scanner"`,`Human`],
	[`"Asteroid Scanner"`,`Human`],
	[`"Tactical Scanner"`,`Human`],
	[`"Surveillance Pod"`,`Human`],
	[`"Cloaking Device"`,`Human`],
	[`"Outfits Expansion"`,`Human`],
	[`"Cargo Expansion"`,`Human`],
	[`"Bunk Room"`,`Human`],
	[`"Small Bunk Room"`,`Human`],
	[`"Brig"`,`Human`],
	[`"Luxury Accommodations"`,`Human`],
	[`"Fuel Pod"`,`Human`],
	[`"Interference Plating"`,`Human`],
	[`"Laser Rifle"`,`Human`],
	[`"Fragmentation Grenades"`,`Human`],
	[`"Security Station"`,`Human`],
	[`"Nerve Gas"`,`Human`],
	[`"Puny"`,`Human`],
	[`"Tear of Skade"`,`Human`],
	[`"Local Map"`,`Human`],
	[`"Pilot's License"`,`Human`],
	[`"Navy License"`,`Human`],
	[`"Navy Auxiliary License"`,`Human`],
	[`"Navy Cruiser License"`,`Human`],
	[`"Navy Carrier License"`,`Human`],
	[`"Militia License"`,`Human`],
	[`"City-Ship License"`,`Human`],
	[`"Supercapacitor"`,`Human`],
	[`"LP036a Battery Pack"`,`Human`],
	[`"LP072a Battery Pack"`,`Human`],
	[`"LP144a Battery Pack"`,`Human`],
	[`"LP288a Battery Pack"`,`Human`],
	[`"LP576a Battery Pack"`,`Human`],
	[`"KP-6 Photovoltaic Panel"`,`Human`],
	[`"KP-6 Photovoltaic Array"`,`Human`],
	[`"nGVF-AA Fuel Cell"`,`Human`],
	[`"nGVF-BB Fuel Cell"`,`Human`],
	[`"nGVF-CC Fuel Cell"`,`Human`],
	[`"nGVF-DD Fuel Cell"`,`Human`],
	[`"nGVF-EE Fuel Cell"`,`Human`],
	[`"RT-I Radiothermal"`,`Human`],
	[`"S3 Thermionic"`,`Human`],
	[`"NT-200 Nucleovoltaic"`,`Human`],
	[`"Dwarf Core"`,`Human`],
	[`"Fission Reactor"`,`Human`],
	[`"Breeder Reactor"`,`Human`],
	[`"Fusion Reactor"`,`Human`],
	[`"Armageddon Core"`,`Human`],
	[`"Stack Core"`,`Human`],
	[`"Energy Blaster"`,`Human`],
	[`"Twin Blaster"`,`Human`],
	[`"Blaster Submunition"`,`Human`],
	[`"Blaster Turret"`,`Human`],
	[`"Quad Blaster Turret"`,`Human`],
	[`"Modified Blaster"`,`Human`],
	[`"Twin Modified Blaster"`,`Human`],
	[`"Modified Blaster Submunition"`,`Human`],
	[`"Modified Blaster Turret"`,`Human`],
	[`"Beam Laser"`,`Human`],
	[`"Laser Turret"`,`Human`],
	[`"Heavy Laser"`,`Human`],
	[`"Heavy Laser Turret"`,`Human`],
	[`"Electron Beam"`,`Human`],
	[`"Electron Turret"`,`Human`],
	[`"Anti-Missile Turret"`,`Human`],
	[`"Heavy Anti-Missile Turret"`,`Human`],
	[`"Particle Cannon"`,`Human`],
	[`"Proton Gun"`,`Human`],
	[`"Proton Fragment"`,`Human`],
	[`"Proton Turret"`,`Human`],
	[`"Plasma Cannon"`,`Human`],
	[`"Plasma Turret"`,`Human`],
	[`"Plasma Repeater"`,`Human`],
	[`"Flamethrower"`,`Human`],
	[`"Flamethrower Projectile"`,`Human`],
	[`"Meteor Missile"`,`Human`],
	[`"Meteor Missile Box"`,`Human`],
	[`"Meteor Missile Launcher"`,`Human`],
	[`"Meteor Missile Pod"`,`Human`],
	[`"Sidewinder Missile"`,`Human`],
	[`"Sidewinder Missile Rack"`,`Human`],
	[`"Sidewinder Missile Launcher"`,`Human`],
	[`"Sidewinder Missile Pod"`,`Human`],
	[`"Javelin"`,`Human`],
	[`"Javelin Storage Crate"`,`Human`],
	[`"Javelin Pod"`,`Human`],
	[`"Javelin Mini Pod"`,`Human`],
	[`"Torpedo"`,`Human`],
	[`"Torpedo Storage Rack"`,`Human`],
	[`"Torpedo Launcher"`,`Human`],
	[`"Torpedo Pod"`,`Human`],
	[`"Typhoon Torpedo"`,`Human`],
	[`"Typhoon Storage Tube"`,`Human`],
	[`"Typhoon Launcher"`,`Human`],
	[`"Typhoon Pod"`,`Human`],
	[`"Heavy Rocket"`,`Human`],
	[`"Heavy Rocket Rack"`,`Human`],
	[`"Heavy Rocket Launcher"`,`Human`],
	[`"Heavy Rocket Pod"`,`Human`],
	[`"Nuclear Missile"`,`Human`],
	[`"Gatling Gun Ammo"`,`Human`],
	[`"Bullet Boxes"`,`Human`],
	[`"Gatling Gun"`,`Human`],
	[`"gbullet"`,`Human`],
	[`"Ka'het Nullifier"`,`Ka'het`],
	[`"Ka'het Ravager Beam"`,`Ka'het`],
	[`"Ka'het Ravager Turret"`,`Ka'het`],
	[`"Ka'het Annihilator"`,`Ka'het`],
	[`"Ka'het Annihilator Turret"`,`Ka'het`],
	[`"Annihilator Projectile"`,`Ka'het`],
	[`"Ka'het EMP Deployer"`,`Ka'het`],
	[`"Ka'het Emergency Deployer"`,`Ka'het`],
	[`"Ka'het Support Cooling"`,`Ka'het`],
	[`"Ka'het Primary Cooling"`,`Ka'het`],
	[`"Ka'het Shield Restorer"`,`Ka'het`],
	[`"Ka'het Grand Restorer"`,`Ka'het`],
	[`"Ka'het MHD Generator"`,`Ka'het`],
	[`"Ka'het Reserve Accumulator"`,`Ka'het`],
	[`"Maeri Engine Nacelles"`,`Ka'het`],
	[`"Ka'het Sustainer Nacelles"`,`Ka'het`],
	[`"Telis Engine Nacelles"`,`Ka'het`],
	[`"Vareti Engine Block"`,`Ka'het`],
	[`"Ka'het Compact Engine"`,`Ka'het`],
	[`"Generator (Candle Class)"`,`Korath`],
	[`"Generator (Furnace Class)"`,`Korath`],
	[`"Generator (Inferno Class)"`,`Korath`],
	[`"Plasma Core"`,`Korath`],
	[`"Double Plasma Core"`,`Korath`],
	[`"Triple Plasma Core"`,`Korath`],
	[`"Small Heat Shunt"`,`Korath`],
	[`"Large Heat Shunt"`,`Korath`],
	[`"Liquid Sodium Cooler"`,`Korath`],
	[`"Systems Core (Tiny)"`,`Korath`],
	[`"Systems Core (Small)"`,`Korath`],
	[`"Systems Core (Medium)"`,`Korath`],
	[`"Systems Core (Large)"`,`Korath`],
	[`"Fuel Processor"`,`Korath`],
	[`"Command Center"`,`Korath`],
	[`"Reasoning Node"`,`Korath`],
	[`"Control Transceiver"`,`Korath`],
	[`"Afterburner (Asteroid Class)"`,`Korath`],
	[`"Afterburner (Comet Class)"`,`Korath`],
	[`"Afterburner (Lunar Class)"`,`Korath`],
	[`"Afterburner (Planetary Class)"`,`Korath`],
	[`"Afterburner (Stellar Class)"`,`Korath`],
	[`"Engine (Meteor Class)"`,`Korath`],
	[`"Bow Drive (Meteor Class)"`,`Korath`],
	[`"Reverser (Asteroid Class)"`,`Korath`],
	[`"Reverser (Comet Class)"`,`Korath`],
	[`"Reverser (Lunar Class)"`,`Korath`],
	[`"Reverser (Planetary Class)"`,`Korath`],
	[`"Reverser (Stellar Class)"`,`Korath`],
	[`"Thruster (Asteroid Class)"`,`Korath`],
	[`"Thruster (Comet Class)"`,`Korath`],
	[`"Thruster (Lunar Class)"`,`Korath`],
	[`"Thruster (Planetary Class)"`,`Korath`],
	[`"Thruster (Stellar Class)"`,`Korath`],
	[`"Steering (Asteroid Class)"`,`Korath`],
	[`"Steering (Comet Class)"`,`Korath`],
	[`"Steering (Lunar Class)"`,`Korath`],
	[`"Steering (Planetary Class)"`,`Korath`],
	[`"Steering (Stellar Class)"`,`Korath`],
	[`"Arkrof GP Hybrid Thruster"`,`Korath`],
	[`"Farves GP Hybrid Thruster"`,`Korath`],
	[`"Gaktem GP Hybrid Thruster"`,`Korath`],
	[`"Nelmeb GP Hybrid Thruster"`,`Korath`],
	[`"Arkrof GP Hybrid Steering"`,`Korath`],
	[`"Farves GP Hybrid Steering"`,`Korath`],
	[`"Gaktem GP Hybrid Steering"`,`Korath`],
	[`"Nelmeb GP Hybrid Steering"`,`Korath`],
	[`"Thermal Repeater Rifle"`,`Korath`],
	[`"Microbot Defense Station"`,`Korath`],
	[`"Grab-Strike Turret"`,`Korath`],
	[`"Shunt-Strike Turret"`,`Korath`],
	[`"Banisher Grav-Turret"`,`Korath`],
	[`"Expeller Grav-Ray"`,`Korath`],
	[`"Warder Anti-Missile"`,`Korath`],
	[`"Fire-Lance"`,`Korath`],
	[`"Blaze-Pike Turret"`,`Korath`],
	[`"Korath Inferno"`,`Korath`],
	[`"Thermal Repeater"`,`Korath`],
	[`"Thermal Repeater Turret"`,`Korath`],
	[`"Piercer Missile"`,`Korath`],
	[`"Piercer Missile Rack"`,`Korath`],
	[`"Piercer Missile Launcher"`,`Korath`],
	[`"Korath Detainer"`,`Korath`],
	[`"Cluster Mine"`,`Korath`],
	[`"Cluster Mine Rack"`,`Korath`],
	[`"Cluster Mine Layer"`,`Korath`],
	[`"Korath Mine Submunition"`,`Korath`],
	[`"Shield Disruptor Turret"`,`Korath`],
	[`"Husk-Slice"`,`Korath`],
	[`"Husk-Slice Turret"`,`Korath`],
	[`"Digger Mining Turret"`,`Korath`],
	[`"Digger Mining Beam"`,`Korath`],
	[`"Langrage Hyper-Heaver"`,`Korath`],
	[`"Heaver Shard"`,`Korath`],
	[`"Heaver Splinter"`,`Korath`],
	[`"Firelight Storage Rack"`,`Korath`],
	[`"Firelight Missile"`,`Korath`],
	[`"Firelight Missile Bank"`,`Korath`],
	[`"Firelight Turning"`,`Korath`],
	[`"Firelight Activated"`,`Korath`],
	[`"Microbot Grinder"`,`Korath`],
	[`"Firestorm Torpedo"`,`Korath`],
	[`"Firestorm Torpedo Rack"`,`Korath`],
	[`"Firestorm Battery"`,`Korath`],
	[`"Nano Strike"`,`Korath`],
	[`"Pug Zapper"`,`Pug`],
	[`"Pug Zapper Turret"`,`Pug`],
	[`"Pug Seeker"`,`Pug`],
	[`"Pug Anti-Missile"`,`Pug`],
	[`"Tier 3 Anti-Missile"`,`Pug`],
	[`"Pug Gridfire Turret"`,`Pug`],
	[`"Pug Akfar Thruster"`,`Pug`],
	[`"Pug Akfar Steering"`,`Pug`],
	[`"Pug Cormet Thruster"`,`Pug`],
	[`"Pug Cormet Steering"`,`Pug`],
	[`"Pug Lohmar Thruster"`,`Pug`],
	[`"Pug Lohmar Steering"`,`Pug`],
	[`"Pug Biodefenses"`,`Pug`],
	[`"Pug Peacekeeping Staff"`,`Pug`],
	[`"Nanotech Battery"`,`Quarg`],
	[`"Antimatter Core"`,`Quarg`],
	[`"Quarg Skylance"`,`Quarg`],
	[`"Quarg Anti-Missile"`,`Quarg`],
	[`"Intrusion Countermeasures"`,`Quarg`],
	[`"Medium Graviton Thruster"`,`Quarg`],
	[`"Medium Graviton Steering"`,`Quarg`],
	[`"Quantum Shield Generator"`,`Quarg`],
	[`"Inhibitor Cannon"`,`Remnant`],
	[`"Inhibitor Turret"`,`Remnant`],
	[`"Thrasher Cannon"`,`Remnant`],
	[`"Thrasher Turret"`,`Remnant`],
	[`"Point Defense Turret"`,`Remnant`],
	[`"EMP Torpedo"`,`Remnant`],
	[`"EMP Torpedo Storage Bay"`,`Remnant`],
	[`"EMP Torpedo Bay"`,`Remnant`],
	[`"Teciimach Canister"`,`Remnant`],
	[`"Teciimach Canister Rack"`,`Remnant`],
	[`"Teciimach Bay"`,`Remnant`],
	[`"Teciimach Pod"`,`Remnant`],
	[`"Ember Tear"`,`Remnant`],
	[`"Crystal Capacitor"`,`Remnant`],
	[`"Millennium Cell"`,`Remnant`],
	[`"Epoch Cell"`,`Remnant`],
	[`"Aeon Cell"`,`Remnant`],
	[`"Thermoelectric Cooler"`,`Remnant`],
	[`"Emergency Ramscoop"`,`Remnant`],
	[`"NDR-114 Android"`,`Remnant`],
	[`"Research Laboratory"`,`Remnant`],
	[`"Quantum Key Stone"`,`Remnant`],
	[`"Salvage Scanner"`,`Remnant`],
	[`"Bellows-Class Afterburner"`,`Remnant`],
	[`"Anvil-Class Engine"`,`Remnant`],
	[`"Crucible-Class Thruster"`,`Remnant`],
	[`"Forge-Class Thruster"`,`Remnant`],
	[`"Smelter-Class Thruster"`,`Remnant`],
	[`"Crucible-Class Steering"`,`Remnant`],
	[`"Forge-Class Steering"`,`Remnant`],
	[`"Smelter-Class Steering"`,`Remnant`],
	[`"Tuning Rifle"`,`Remnant`],
	[`"Void Rifle"`,`Remnant`],
	[`"Void Sprite Parts"`,`Remnant`],
	[`"Remnant License"`,`Remnant`],
	[`"Remnant Capital License"`,`Remnant`],
	[`"Fate Sealer"`,`Rulei`],
	[`"Fate Sealer Activated"`,`Rulei`],
	[`"Fate Divider"`,`Rulei`],
	[`"Fate Divider Activated"`,`Rulei`],
	[`"Abyssal Composer"`,`Rulei`],
	[`"Small EM Battery"`,`Sheragi`],
	[`"Large EM Battery"`,`Sheragi`],
	[`"Small Hybrid Cooling"`,`Sheragi`],
	[`"Large Hybrid Cooling"`,`Sheragi`],
	[`"Fission Drive"`,`Sheragi`],
	[`"Fusion Drive"`,`Sheragi`],
	[`"Electronic Warfare System"`,`Sheragi`],
	[`"Dragonflame Cannon"`,`Sheragi`],
	[`"Sheragi Anti-Missile"`,`Sheragi`],
	[`"Particle Waveform Turret"`,`Sheragi`],
	[`"Shard Fabricator"`,`Sheragi`],
	[`"Shard inactive"`,`Sheragi`],
	[`"Heavy Ion Cyclotron"`,`Sheragi`],
	[`"Heavy Ion Fragment"`,`Sheragi`],
	[`"Plankton Mouth"`,`Vyrmeid`],
	[`"Boomerang Organ"`,`Vyrmeid`],
	[`"Astral Mouth"`,`Vyrmeid`],
	[`"Sunbeam"`,`Wanderer`],
	[`"Sunbeam Turret"`,`Wanderer`],
	[`"Dual Sunbeam Turret"`,`Wanderer`],
	[`"Moonbeam"`,`Wanderer`],
	[`"Moonbeam Turret"`,`Wanderer`],
	[`"Wanderer Anti-Missile"`,`Wanderer`],
	[`"Thunderhead Launcher"`,`Wanderer`],
	[`"Thunderhead Missile"`,`Wanderer`],
	[`"Thunderhead"`,`Wanderer`],
	[`"Thunderhead Storage Array"`,`Wanderer`],
	[`"Small Biochemical Cell"`,`Wanderer`],
	[`"Large Biochemical Cell"`,`Wanderer`],
	[`"Red Sun Reactor"`,`Wanderer`],
	[`"Yellow Sun Reactor"`,`Wanderer`],
	[`"White Sun Reactor"`,`Wanderer`],
	[`"Blue Sun Reactor"`,`Wanderer`],
	[`"Bright Cloud Shielding"`,`Wanderer`],
	[`"Dark Storm Shielding"`,`Wanderer`],
	[`"Wanderer Ramscoop"`,`Wanderer`],
	[`"Wanderer Heat Sink"`,`Wanderer`],
	[`"Type 1 Radiant Thruster"`,`Wanderer`],
	[`"Type 2 Radiant Thruster"`,`Wanderer`],
	[`"Type 3 Radiant Thruster"`,`Wanderer`],
	[`"Type 4 Radiant Thruster"`,`Wanderer`],
	[`"Type 1 Radiant Steering"`,`Wanderer`],
	[`"Type 2 Radiant Steering"`,`Wanderer`],
	[`"Type 3 Radiant Steering"`,`Wanderer`],
	[`"Type 4 Radiant Steering"`,`Wanderer`],
	[`"Wanderer Outfits License"`,`Wanderer`],
	[`"Wanderer License"`,`Wanderer`],
	[`"Wanderer Military License"`,`Wanderer`],
	[`"Pincer"`,`Whispering Void`]
])